#!/usr/bin/env bash
# Always filing in the passwd
file="/etc/passwd"
while IFS= read -r line; do
	user=$(echo "$line" | cut -d ':' -f1)
	gid=$(echo "$line" | cut -d ':' -f4)
	dir=$(echo "$line" | cut -d ':' -f6)
	shell=$(echo "$line" | cut -d ':' -f7)
	uid=$(echo "$line" | cut -d ':' -f3)
	pass=$(echo "$line" | cut -d ':' -f2)
	info=$(echo "$line" | cut -d ':' -f5)
