#!/usr/bin/env bash
# print best school until the time and print hi 

i=1

while [ "$i" -lt 11 ]; do

	  echo "Best School"

	    

	    # if statement to print Hi when i is 9

	      if [ "$i" -eq 9 ]; then

		          echo "Hi"

			    fi



			      ((i++))

		      done
