#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and: 



i=1

while [ "$i" -lt 11 ]; do

	    # if the value is 4:bad luck 

	        if [ "$i" -eq 4 ]; then

			        echo "bad luck"

				    elif [ "$i" -eq 8 ]; then 

					            echo "good luck"

						        else

								        echo "Best School"

									    fi



									        ((i++))

									done 
