#!/usr/bin/env bash
# Bash script that loops from 1 to 20 and: 



i=1

while [ "$i" -lt 21 ]; do

	    # if the value is 4:bad luck 

	        case "$i" in 

			        4)

					           echo "$i"

						              echo "bad luck from China"

							                 ;;

									         9)

											             echo "$i"

												                 echo "bad luck from Japan"

														            ;;

															            17)

																	                echo "$i"

																			            echo "bad luck from Italy"

																				                ;;

																						        *)

																								            echo "$i"

																									                ;;

																											        esac

																												        

																												    ((i++))

																											    done 
