#!/usr/bin/env bash
#A bash file that gives you info about a file School 



file="school"



# check if the file wxits 

if [ -e "$file" ];then 

	   echo "school file exists"



	     # checks if file is empty

	       if [ ! -s "$file" ]; then

		           echo "school file is empty"



			       # checks if file is a regular file

			           if [ -f "$file" ]; then

					         echo "school is a regular file"

						     fi  



						       else



							           echo "school file is not empty"



								       # checks if file is a regular file

								           if [ -f "$file" ]; then

										         echo "school is a regular file"

											     fi  

											       

											       fi



										       else 

											           echo "school file does not exist"



fi 
